Integrationtests
pophaax/sailingrobot pull request #49
Opened 2017-07-20 06:53 UTC by viktorhalonnroth

Integrationtest and CAN Nodes

2017-07-20 12:32 UTC, kemar44 requested changes
In the whole thing, it's seemed good :) I'm a little picky but the idea is too help the next people who reads your code to understand the whole thing you already understand currently ;) !
Just some changes where there is some fault.
When you use a function in another one, make sure to declare the first one before the second. It's easier to understand.
I'm not sure you can let processMessage empty because it's processing in the messagebus file (se th efunction processMessages in MessageBus.cpp).
Don't hesitate to write just few commented lines and referenced the informations which is too long to explain.
Don't hesitate to tell me if you don't understand one of my review and I will explain ;)

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +
To justify, maybe you can put the document on a reference.
Because, we could not know what is behind this values. I know you can't explain the whole thing but just show from where 1900, 1950, 1150 and 1110 values correspond for the maestro controller ?

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +
In general, It's better to declare first the functions you use like sendArduinoData, checkCanbusFor, mapInterval and sendFeedback.
Then, the one who reads knows that you create this function and what deals with it.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +  float c = -361.0000;
The name of the variables are not explicit. Could you find a completed name to understand without comment the function ? Otherwise, comment the value or put a document in reference.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +  float b2 = -0.6455;
The name of the variables are not explicit. Could you find a completed name to understand without comment the function ? Otherwise, comment the value or put a reference.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +
If you can do as you 've done below, it will be enough.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +
Except sendArduinoData

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +
Just define RC as Remote Controller, it could not be implicit for the reader

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +      //Serial.println("Sent feedback");
This print is used for something like tests ? If not delete it.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +const int WINGSAIL_MAESTRO_MIN_TARGET = 1110;
To justify, maybe you can put the document on a reference.
Because, we could not know what is behind this values. I know you can't explain the whole thing but just show from where 1900, 1950, 1150 and 1110 values correspond for the maestro controller ?
If you can do as you've done below, it will be enough.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +     stepLen = 1;
You can complete the name "stepLength" , 2 letter more won' be complicated for the code :)

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +
As before, if you can move the used function (below) as first declared function, it will be easier to understand the functions above.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +float mapInterval(float val, float fromMin, float fromMax, float toMin, float toMax) {
Maybe used this function already declared in the file ArduinoSketchASPire.
That's avoid to declare it again for the feedback tests.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +  moveWingsail (-13);
Maybe change the name of moveWingsail, because we can think it the same function in ArduinoSketcheASPire which using a CAN message, or here, the input is an angle.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +
Explain in comment the different states of the test.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/functions.h
> +  float  x = (int)maxAngle % (int)stepLen;
Change the "(int)" to a "static_cast<int>(variable)" (see  https://drive.google.com/open?id=1A9aAUvKBZoTIWU7Yi_jwe7fmMqUd83ApapPWncYp_74)

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +#include <SoftwareSerial.h>
Set an introduction which explain the purpose of the file and comment you want to say.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +#include <SoftwareSerial.h>
Make an introduction with the purpose of the file and the comments on it if you want to add some.

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +float mapInterval(float val, float fromMin, float fromMax, float toMin, float toMax) {
You can maybe make a library for the function you always used as mapInterval and moveWingsail/rudder . Also, to avoid the declaration of moveWingsail/rudder with can message or angle input, you could define a function which process the can message to get the angle which be processed in an other function moveWingsail/Rudder

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +    int i = 0;
Same as before, explain what you test on each part of your code. A line of comment for a group of code line is just enough

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/ActuatorNodeASPire.h
You can also private the variables rudderAngle, wingsailAngle and windvane self steering on. That's avoid a possible interaction problem by although there is no possible problem. It's just a safety margin for protecting the variables.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANAISNode.cpp
> +  std::cout << "HEJ" << std::endl;
I don't know if HEJ is useful :)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANAISNode.cpp
> +
The idea of process message, is to recognize the message you have sent and then call the function below who processing the messages.
If I remember, the process message it's automatic processus for each Node. So, if there is nothing in process Message, it should not enter in the process N2kmessage

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANAISNode.cpp
> +void CANAISNode::parsePGN129038_129039(N2kMsg& nMsg, AISVessel& vessel) {
Ok, it's not problem to understand after some reflexion, but it will be better if there is a comment or a document explaining the composition of N2K message.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANAISNode.cpp
> +    if (PRINT) {
PRINT still needed or not ? if not delete it :)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANAISNode.h
> +  CANAISNode(MessageBus& msgBus, CANService& canService, double loopTime);
if loopTime is already a double, you can just put "0.5" or ".5" to represent 500 milliseconds. 
No need to make a conversion which use more processor "node->m_LoopTime*1f/1000" at l81 of CANAISNode.cpp

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +*			701, 702, (more to be added later?)
Don't know for now ;)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +	m_RC = DATA_OUT_OF_RANGE;
You can name RC : RemoteController. It's implicit for you but no the following readers of the code.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +
The idea of process message, is to recognize the message you have sent and then call the function below who processing the messages.
If I remember, the process message it's automatic processus for each Node. So, if there is nothing in process Message, it should not enter in the process N2kmessage

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +	if (msg.id == 701) {
switch case maybe more adapted to add after other message id. Also if there is no commented code used, so no commented code needs :) .

2017-07-20 12:32 UTC, kemar44 commented on ArduinoSketches/FeedbackTestScript/FeedbackTestScript.ino
> +  pinMode (RC_CONTROLL_OFF_PIN, INPUT);
RC -> RemoteController and Control

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +			if( node->m_RudderFeedback == node->DATA_OUT_OF_RANGE &&  node->m_WindvaneSelfSteerAngle == node->DATA_OUT_OF_RANGE &&
I'm not sure you need to declare the constant defined DATA OUT OF RANGE with the node pointed if it's in the code ad a constant. But I don't really know if that's created bugs.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +/*
Delete the unused commented code line .

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.h
> +	//float mapInterval(float val, float fromMin, float fromMax, float toMin, float toMax);
Delete the unused commented  line

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +			timer.sleepUntil(node->m_TimeBetweenMsgs*1.0f / 1000);
See if the timebetweenmsg can be updated in the database by a configuration of the node. Moreover, usually it's called Looptime in the other node, to avoid the confusion between each nodes ;)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANFeedbackReceiver.cpp
> +}
If unused commented line, delete it

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANSolarTrackerNode.cpp
> +		StateMessage* stateMsg = (StateMessage*) message;
As a comment, process message just recognize the message type and then you process the informations in another function which do it.
It just the form in other nodes, that's why I insist :)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANSolarTrackerNode.cpp
> +				node->m_Lon == node-> DATA_OUT_OF_RANGE ||
I'm not sure you need to declare the constant defined DATA OUT OF RANGE with the node pointed if it's in the code ad a constant. But I don't really know if that's created bugs.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANSolarTrackerNode.cpp
> +
Need a CAN Frame receiver if not used ?

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANSolarTrackerNode.h
> +#pragma once
Introduction to understand what is the purpose of this file and the comments if you want to add some

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANSolarTrackerNode.cpp
> +#include "CANSolarTrackerNode.h"
Introduction to understand the purpose of the code and comments if you want :)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANFeedbackReceiver.cpp
>  #include "CANFeedbackReceiver.h"
Introduction for the file : purpose and comment you want to add about the file

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.h
> +#include "Hardwares/CAN_Services/CANService.h"
Introduction purpose and comments you want to make

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANFeedbackReceiver.cpp
> +{
You don't register the messages you listen with this Node

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +
You don't register the message that you listen with this node

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANAISNode.cpp
> +      AISVessel v1;
you don't register the message for the node

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CANWindsensorNode.cpp
> +  msgBus.registerNode(*this, MessageType::DataRequest);
A comment on the lines below, you can make a switch case for the if else form. :)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CAN_Services/CANService.cpp
> +bool CANService::ParseFastPkg(CanMsg& msg, N2kMsg& nMsg) { // Taken from the CANBUS repo made by Viktor Måsala
Ok, it's well commented and I understand roughly what it's about despite of the lack of knowledge about it. Maybe a source or reference document could help if anyone wants to understand the whole thing.
Also, this function is called and then declared. The best way is to see first the function and then indicate where it's used (here run() ). 
Moreover, although there is no description of the file, we could had one to understand what the file deals with.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CAN_Services/MsgFunctions.cpp
> +	if(Cmsg.header.length)
Add just a little description on the file (purpose, comment on it)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Hardwares/CAN_Services/N2kMsg.h
> +typedef std::tuple<uint32_t,uint8_t> IDsID;
Add a little description of the file (purpose and comment on it)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Math/Utility.cpp
> +float Utility::mapInterval(float val, float fromMin, float fromMax, float toMin, float toMax) {
Maybe find a reference on the equation as explained below

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/MessageBus/MessageBus.cpp
> +					// if (!(msgToString(msg->messageType())=="SolarData")) {
Delete commented line unused

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Messages/AISDataMsg.h
> +// #ifndef AISDATAMSG_H
Delete unused commented line

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Messages/ArduinoDataMsg.h
> +	int RC() const  { return m_RC; }
Ok, maybe the same for the variable above.
RC : RemoteController

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Messages/SolarDataMsg.h
> +  int hour() { return m_Hour; }
int hour() const { return m_hour} That's make sure to avoid the modification of the data, I think

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/IntegrationTests/ArduinoIntegrationTest.cpp
> +        } else if (type == MessageType::ArduinoData) {
ok, you could make a switch case if you want and also divided each message process in other function but it's fine.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/IntegrationTests/ArduinoIntegrationTest.cpp
> +	   } else if (it.second == -3000) {
ok, I supposed wfunctions are from a library. Can you just explain what it's about :) a little line of comment should be enough I think.

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/IntegrationTests/ArduinoIntegrationTest.cpp
> +#include "Messages/ActuatorControlASPireMessage.h"
Add a little description of the file : purpose, comments on the file

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/IntegrationTests/ArduinoIntegrationTest.cpp
> +        //windvaneAngle16 = stoi(menuValues["Windvane Angle"]);
To see for the wind vane

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/IntegrationTests/CANAISTest.cpp
> +// #pragma once
Add a little description on the file : purpose and your comments. 
Also I don't understand how you tests. Need to see that with you

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/IntegrationTests/CANAISTest.cpp
> +  std::cout << "MMMMMMMMMMMMMMMMMMM" << std::endl;
A lot of M isn't it ? :) I don't think it's useful otherwise, I will return learn my programming lessons !

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/unit-tests/CanNodesSuite.h
> +    // std::vector<uint32_t> canMessages; // = {700, 701};
Commented code = unused line --> Trash ? :)

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/unit-tests/TestMocks/MockCANPGNReceiver.h
> +#pragma once
Little description and I need to see with you because I don't know how you test with this .h

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/Tests/unit-tests/TestMocks/MockNode.h
> +	double m_latitude;
Missing m_heading ?

2017-07-20 12:32 UTC, kemar44 commented on NavigationSystem/makefile
> +export CPPFLAGS                = -g -ggdb -Wall -pedantic -Werror -std=gnu++14
Normal ?

2017-07-20 12:32 UTC, kemar44 commented on createtables.sql
> +
maybe more explicit term for the table.
Also, add in the recent table created in Google drive, in tab New_DB_ASPire :  https://docs.google.com/spreadsheets/u/2/d/1QuP39-nvPkAPv7n1L8Q06pufJ0cedYxDur2Ux6r_IL4/edit?usp=drive_web

2017-07-21 07:53 UTC, MattssonV commented on NavigationSystem/Tests/IntegrationTests/CANAISTest.cpp
> +// #pragma once
Yes, will add description!

2017-07-21 07:54 UTC, MattssonV commented on NavigationSystem/Messages/SolarDataMsg.h
> +  int hour() { return m_Hour; }
Yeah, probably, good idea!

2017-07-21 07:55 UTC, MattssonV commented on NavigationSystem/Hardwares/CANSolarTrackerNode.cpp
> +
No, wont be necessary, I will remove it

2017-07-21 07:59 UTC, MattssonV commented
Looked over your comments now Marc! Since I am working on my own branch now (AISProcessing) a lot of the code here is outdated but still some good points made! I will make sure to fix it in my branch! :)

2017-07-25 07:54 UTC, kemar44 approved these changes
For Viktor Lonnroth, I agree with all your modifications however,  you have a little problem with the constructor of ArduinoDataMsg.

2017-07-25 07:54 UTC, kemar44 commented on NavigationSystem/Messages/ArduinoDataMsg.h
> +		:Message(MessageType::ArduinoData, souRadio_ControllereID, destinationID), m_pressure(pressure), m_rudder(rudder), m_sheet(sheet), m_battery(battery), m_Radio_Controller(Radio_Controller)
I think there is a problem when you change the RC which interfer with "sourceID"

2017-07-26 11:29 UTC, legalmael requested changes
- Create a new branch from this branch.
- Then delete all the news files that are not related with the integrations tests.
- Merge again the develop branch inside this new branch. 
- Check the code indentation, on a text editor for c++ like sublime.
- Check the header comment of all modified files is updated.
- Take into account the comments of the current pull request.
- Create a new pull request.

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/Hardwares/ActuatorNodeASPire.h
> +		bool WindvaneSelfSteeringOn;
Const to be declare first (in the private section).
Naming convention : "Class data members are prefixed with m_, followed by a lowercase letter"

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/Hardwares/ActuatorNodeASPire.cpp
>          (Cmsg.data[3] = angle_16 >> 8);
Why are you using the same variable for the sail angle and rudder angle ? Is it not easier to use two variable instead ?

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/Hardwares/ActuatorNodeASPire.cpp
> +        uint16_t angle_16 = Utility::mapInterval (rudderAngle, -MAX_RUDDER_ANGLE, MAX_RUDDER_ANGLE, 0 , INT16_SIZE);
Is it possible to have signed values sent in the CANbus, as we previously discussed ?

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +*			701, 702, (more to be added later?)
Why are we using two CAN id numbers ?

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +			timer.sleepUntil(node->m_TimeBetweenMsgs*1.0f / 1000);
I agree and the line with "timer.sleepUntil" should be after the process of the node functions (at the end of the while, just before the reset).

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/Hardwares/CAN_Services/CANService.cpp
> +        done = false;
What is done or not ?

2017-07-26 11:29 UTC, legalmael commented on NavigationSystem/MessageBus/MessageBus.cpp
> +					// if (!(msgToString(msg->messageType())=="SolarData")) {
To check

2017-08-03 12:58 UTC, merged