Integrationtests for merge
pophaax/sailingrobot pull request #50
Opened 2017-07-31 07:43 UTC by viktorhalonnroth

Made all the changes for the merge with develop

2017-08-02 08:24 UTC, legalmael requested changes
Some questions and changes requested.
Tell me when you want to go threw them together. I will be in my office this afternoon.

2017-08-02 08:24 UTC, legalmael commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +double wingsailAngleRatio = 65535 / MAX_WINGSAIL_ANGLE;
Use INT16_SIZE instead of 65535.

2017-08-02 08:24 UTC, legalmael commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +void loop()
Need an explication for what is inside the loop. 
I don't understand the delay.

2017-08-02 08:24 UTC, legalmael commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +      angle16 = getWingsailFeedback();
change the variables names angle16 to "wingsailFeedback16" or something similar.

2017-08-02 08:24 UTC, legalmael commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +          Serial.print("Received rudder angle: "); Serial.println(rudderAngel);
Comment the prints line ???

2017-08-02 08:24 UTC, legalmael commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +  maestro.getErrors();
What do you do with the maestro errors ?

2017-08-02 08:24 UTC, legalmael commented on ArduinoSketches/FeedbackMapScript/FeedbackMapScript.ino
> +#include "functions.h"
function.h ?

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/Hardwares/CANArduinoNode.cpp
> +
use the mutex to lockthe data when writing.
"std::lock_guard<std::mutex> lock(m_lock)"

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/Hardwares/CAN_Services/CANService.cpp
> +  bool done;
change the name of the done variable. What is done ?

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/MessageBus/MessageDeserialiser.cpp
> +
Is it used ? What for ?

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/MessageBus/MessageDeserialiser.h
> +	uint8_t* data();
Same here. What is it for ?

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/Tests/IntegrationTests/IntegrationTestASPire.cpp
> +				const ArduinoDataMsg* arduinomsg = dynamic_cast<const ArduinoDataMsg*>(message);
Why not a boolean value ?
Why ArduinoDataMsg and not ASPireActuatorFeedbackMsg ?

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/Tests/IntegrationTests/IntegrationTestASPire.cpp
> +		m_SensorValues["Rudder Angle"] = -2000;
instead of using -2000, use a variable : DATA_OUT_OF_RANGE.

2017-08-02 08:24 UTC, legalmael commented on NavigationSystem/Tests/IntegrationTests/IntegrationTestASPire.cpp
> +	float m_RudderAngle = -2000;
Why "= -2000" here ? 
Should be only in the constructor.

2017-08-02 11:16 UTC, viktorhalonnroth commented on ArduinoSketches/ArduinoSketchASPire/ArduinoSketchASPire.ino
> +  maestro.getErrors();
Check if it clears errors

2017-08-02 11:25 UTC, viktorhalonnroth commented on NavigationSystem/Hardwares/CAN_Services/CANService.h
> +
Remove

2017-08-03 12:57 UTC, legalmael approved these changes

2017-08-03 12:58 UTC, merged